version: '3.3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes-network

  app:
    build: .
    command: [sh, -c, "npm run run-migrations:prod && npm run start:prod"]
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres
    networks:
      - notes-network

volumes:
  postgres_data:

networks:
  notes-network:
    driver: bridge
